---
apiVersion: hub.traefik.io/v1alpha1
kind: APIGateway
metadata:
  name: my-gateway
  labels:
    area: crm
spec:
  apiAccesses:
    - crm-all
    - crm-internal
    - admins
    - custom-pick
  customDomains:
    - gateway.kubecon.demo.traefiklabs.tech
