---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: crm-internal
spec:
  groups:
    - internal
  apiSelector:
    matchLabels:
      module: crm
      area: employee

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: crm-all
spec:
  groups:
    - crm-user
  apiCollectionSelector:
    matchLabels:
      module: crm

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: custom-pick
spec:
  groups:
    - support
  apis:
    - name: world-time-api-external-name
      namespace: apps
  apiSelector:
    matchExpressions:
      - key: area
        operator: In
        values:
          - flights
          - tickets

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: admins
spec:
  groups:
    - admin
  apiSelector:
    matchExpressions:
      - key: area
        operator: Exists
