---
apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-apispec
  namespace: apps
data:
  openapi.yaml: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Employee
      description: Traefik Airlines Employee API
      contact:
        name: Traefik Airlines Support
        url: 'https://traefik.io/'
      license:
        name: Apache 2.0
        url: 'https://spdx.org/licenses/Apache-2.0.html'
    servers:
      - url: https://api.traefik.localhost
    paths:
      /employees:
        get:
          summary: Get employees
          operationId: getEmployees
          tags:
            - employees
          parameters:
            - name: limit
              in: query
              description: How many items to return at one time (max 100)
              required: false
              schema:
                type: integer
                maximum: 100
                format: int32
          responses:
            '200':
              description: A paged array of employees
              headers:
                x-next:
                  description: A link to the next page of responses
                  schema:
                    type: string
              content:
                application/json:    
                  schema:
                    $ref: "#/components/schemas/Employees"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
        post:
          summary: Create a employee
          operationId: createEmployee
          tags:
            - employees
          responses:
            '201':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
      /employees/{employeeId}:
        get:
          summary: Info for a specific employee
          operationId: showEmployeeById
          tags:
            - employees
          parameters:
            - name: employeeId
              in: path
              required: true
              description: The id of the employee
              schema:
                type: string
          responses:
            '200':
              description: Expected response to a valid request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Employee"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
        put:
          summary: Update an employee
          operationId: updateEmployee
          tags:
            - employees
          parameters:
            - name: employeeId
              in: path
              required: true
              description: The id of the employee
              schema:
                type: string
          responses:
            '200':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
        delete:
          summary: Delete a employee
          operationId: deleteEmployee
          tags:
            - employees
          parameters:
            - name: employeeId
              in: path
              required: true
              description: The id of the employee
              schema:
                type: string
          responses:
            '200':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
    components:
      schemas:
        Employee:
          type: object
          required:
            - id
            - firstName
            - lastName
          properties:
            id:
              type: integer
              format: int64
            firstName:
              type: string
            lastName:
              type: string
            role:
              type: string
            homeAirport:
              type: string
        Employees:
          type: array
          maxItems: 100
          items:
            $ref: "#/components/schemas/Employee"
        Error:
          type: object
          required:
            - message
          properties:
            message:
              type: string
