---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-openapi
  namespace: apps
data:
  openapi.yaml: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Tickets
      description: Traefik Airlines Tickets API
      contact:
        name: Traefik Airlines Support
        url: 'https://traefik.io/'
      license:
        name: Apache 2.0
        url: 'https://spdx.org/licenses/Apache-2.0.html'
    servers:
      - url: https://api.traefik.localhost
    paths:
      /tickets:
        get:
          summary: Retrieve tickets
          operationId: getTickets
          tags:
            - tickets
          parameters:
            - name: limit
              in: query
              description: How many items to return at one time (max 100)
              required: false
              schema:
                type: integer
                maximum: 100
                format: int32
          responses:
            '200':
              description: A paged array of tickets
              headers:
                x-next:
                  description: A link to the next page of responses
                  schema:
                    type: string
              content:
                application/json:    
                  schema:
                    $ref: "#/components/schemas/Tickets"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
        post:
          summary: Create a ticket
          operationId: createTicket
          tags:
            - tickets
          responses:
            '201':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
      /tickets/{ticketId}:
        get:
          summary: Info for a specific ticket
          operationId: showTicketById
          tags:
            - tickets
          parameters:
            - name: ticketId
              in: path
              required: true
              description: The id of the ticket
              schema:
                type: string
          responses:
            '200':
              description: Expected response to a valid request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Ticket"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
        put:
          summary: Update a ticket
          operationId: updateTicket
          tags:
            - tickets
          parameters:
            - name: ticketId
              in: path
              required: true
              description: The id of the ticket
              schema:
                type: string
          responses:
            '200':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
        delete:
          summary: Delete a ticket
          operationId: deleteTicket
          tags:
            - tickets
          parameters:
            - name: ticketId
              in: path
              required: true
              description: The id of the ticket
              schema:
                type: string
          responses:
            '200':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
    components:
      schemas:
        Ticket:
          type: object
          required:
            - id
            - flightCode
          properties:
            id:
              type: integer
              format: int64
            flightCode:
              type: string
            fare:
              type: integer
              format: int64
            class:
              type: string
            available:
              type: integer
              format: int64
            total:
              type: integer
              format: int64
        Tickets:
          type: array
          maxItems: 100
          items:
            $ref: "#/components/schemas/Ticket"
        Error:
          type: object
          required:
            - message
          properties:
            message:
              type: string
           