---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-hub
  namespace: traefik-hub
spec:
  releaseName: traefik-hub
  chart:
    spec:
      chart: traefik-hub
      version: v2.7.0
      sourceRef:
        kind: HelmRepository
        name: traefik-hub
  interval: 50m
  install:
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    additionalArguments:
      - --hub.metrics.opentelemetry.insecure
      - --hub.metrics.opentelemetry.address=prometheus.monitoring:9090
      - --hub.metrics.opentelemetry.path=/api/v1/otlp/v1/metrics
    service:
      type: LoadBalancer
      # Needed on local Kind k8s cluster.
      # Can be removed or customized as needed on other k8s cluster.
      ports:
        - port: 80
          name: web
          targetPort: web
          nodePort: 30000
        - port: 443
          name: websecure
          targetPort: websecure
          nodePort: 30001
