{
 "title": "API",
 "tags": [ "hub" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "api_name", "label": "API Name", "query": { "query": "label_values(api_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Total # of requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_hub_api_requests_total{api_name=~\"$api_name\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(email) (traefik_hub_api_requests_total{api_name=~\"$api_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per users",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (email) (rate(traefik_hub_api_requests_total{api_name=~\"$api_name\"}[1m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (rate(traefik_hub_api_requests_total{api_name=~\"$api_name\"}[1m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (code) (rate(traefik_hub_api_requests_total{api_name=~\"$api_name\"}[1m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average error rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(increase(traefik_hub_api_requests_total{api_name=~\"$api_name\", code!~\"2.+\"}[$__range]))/sum(increase(traefik_hub_api_requests_total{api_name=~\"$api_name\", code=~\".+\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per API",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_hub_api_requests_total{api_name=~\"$api_name\"}[1m]))",
     "legendFormat": "All requests"
    },
    {
     "expr": "sum(rate(traefik_hub_api_requests_total{api_name=~\"$api_name\", code!~\"2.*\"}[1m]))",
     "legendFormat": "Non 2xx Requests"
    }
   ]
  },
  {
   "title": "Latency per API",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (api_name) (rate(traefik_hub_api_requests_duration_milliseconds_sum{api_name=~\"$api_name\"}[1m])) > 0",
     "legendFormat": "{{api_name}}"
    }
   ]
  }
 ]
}