{
 "title": "Users",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "email", "label": "Email", "query": { "query": "label_values(email)" } },
   {
    "name": "token_name",
    "label": "Token Name",
    "query": {
     "query": "label_values(traefik_hub_api_requests_duration_milliseconds_bucket{email=~\"$email\"},token_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "# Tokens",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traefik_hub_api_keys_ratio{user_email=\"$email\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total # of requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_hub_api_requests_total{email=~\"$email\", token_name=~\"$token_name\", code=~\".+\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# APIs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (api_name) (traefik_hub_api_requests_total{email=~\"$email\", token_name=~\"$token_name\"}))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average error rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(increase(traefik_hub_api_requests_total{email=~\"$email\", token_name=~\"$token_name\", code!~\"2.+\"}[$__range]))/sum(increase(traefik_hub_api_requests_total{email=~\"$email\", token_name=~\"$token_name\", code=~\".+\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per API",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (api_name) (rate(traefik_hub_api_requests_total{email=~\"$email\", token_name=~\"$token_name\",code=~\".+\"}[1m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per Token",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (token_name) (rate(traefik_hub_api_requests_total{email=~\"$email\", token_name=~\"$token_name\",code=~\".+\"}[1m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 22, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (code, api_name, method, token_name) (rate(traefik_hub_api_requests_total{email=~\"$email\", token_name=~\"$token_name\",code=~\".+\"}[1m])) > 0",
     "legendFormat": "[{{code}}] {{api_name}} {{method}} {{token_name}}"
    }
   ]
  }
 ]
}