---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: customer-api-versioned
  namespace: apps
  labels:
    area: customers
    module: crm
spec:
  pathPrefix: "/customers-versioned"
  currentVersion: v2-1-0

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: v1
  namespace: apps
spec:
  apiName: customer-api-versioned
  release: 1.0.0
  title: "Catch-all"
  service:
    name: customer-app
    port:
      number: 3000
    openApiSpec:
      url: http://customer-app.apps:3000/openapi.yaml

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: v2
  namespace: apps
spec:
  apiName: customer-api-versioned
  release: 2.0.0
  title: "URI path"
  routes:
    - pathPrefix: /v2
  stripPathPrefix: true
  service:
    name: customer-app-v2
    port:
      number: 3000
    openApiSpec:
      path: /openapi.yaml

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: v3
  namespace: apps
spec:
  apiName: customer-api-versioned
  release: 3.0.0
  title: "Query param"
  routes:
    - queryParams:
        v: "3"
  service:
    name: customer-app-v3
    port:
      number: 3000
    openApiSpec:
      path: /openapi.yaml

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: v4
  namespace: apps
spec:
  apiName: customer-api-versioned
  release: 4.0.0
  title: "Header with multiple blocks & query params"
  routes:
    - headers:
        Version: "4"
    - queryParams:
        v: "4"
        lang: hu
    - pathPrefix: /v4
  stripPathPrefix: true
  service:
    name: customer-app-v4
    port:
      number: 3000
    openApiSpec:
      path: /openapi.yaml

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: v2-1-0
  namespace: apps
spec:
  apiName: customer-api-versioned
  release: 2.1.0
  title: "URI path + CORS + Headers"
  routes:
    - pathPrefix: /v2.1
  stripPathPrefix: true
  service:
    name: customer-app-v2
    port:
      number: 3000
    openApiSpec:
      path: /openapi.yaml
  cors:
    allowCredentials: true
    allowHeaders:
      - '*'
    allowMethods:
      - GET
      - HEAD
      - POST
      - PUT
      - PATCH
      - DELETE
      - CONNECT
      - OPTIONS
      #- TRACE
    allowOriginList:
      - '*'
    maxAge: 0
  headers:
    request:
      set:
        "X-Request-Header": "Extra request header"
        "X-Username": "Somebody"
      delete:
      - "Unnecessary-Request-Header"
    response:
      set:
        "X-Response-Header": "Extra response header"
        "X-API-Server": "Traefik Hub"
      delete:
      - "Secret-Response-Header"
