---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-apispec
  namespace: apps
data:
  openapi.yaml: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Customers
      description: Traefik Airlines Customer API
      contact:
        name: Traefik Airlines Support
        url: 'https://traefik.io/'
      license:
        name: Apache 2.0
        url: 'https://spdx.org/licenses/Apache-2.0.html'
    servers:
      - url: https://api.traefik.localhost
    paths:
      /customers:
        get:
          summary: Retrieve customers
          operationId: getCustomers
          tags:
            - customers
          parameters:
            - name: limit
              in: query
              description: How many items to return at one time (max 100)
              required: false
              schema:
                type: integer
                maximum: 100
                format: int32
          responses:
            '200':
              description: A paged array of customers
              headers:
                x-next:
                  description: A link to the next page of responses
                  schema:
                    type: string
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Customers"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
        post:
          summary: Create a customer
          operationId: createCustomer
          tags:
            - customers
          responses:
            '201':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
      /customers/{customerId}:
        get:
          summary: Info for a specific customer
          operationId: showCustomerById
          tags:
            - customers
          parameters:
            - name: customerId
              in: path
              required: true
              description: The id of the customer
              schema:
                type: string
          responses:
            '200':
              description: Expected response to a valid request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Customer"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
        put:
          summary: Update a customer
          operationId: updateCustomer
          tags:
            - customers
          parameters:
            - name: customerId
              in: path
              required: true
              description: The id of the customer
              schema:
                type: string
          responses:
            '200':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
        delete:
          summary: Delete a customer
          operationId: deleteCustomer
          tags:
            - customers
          parameters:
            - name: customerId
              in: path
              required: true
              description: The id of the customer
              schema:
                type: string
          responses:
            '200':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
    components:
      schemas:
        Customer:
          type: object
          required:
            - id
            - firstName
            - lastName
          properties:
            id:
              type: integer
              format: int64
            firstName:
              type: string
            lastName:
              type: string
            points:
              type: integer
              format: int64
            status:
              type: string
        Customers:
          type: array
          maxItems: 100
          items:
            $ref: "#/components/schemas/Customer"
        Error:
          type: object
          required:
            - message
          properties:
            message:
              type: string