---
apiVersion: hub.traefik.io/v1
kind: API
metadata:
  name: world-time-api-external-name
  namespace: apps
  labels:
    area: external
    external: name
spec:
  pathPrefix: /world-time-api
  service:
    openApiSpec:
      url: https://worldtimeapi.org/api
    name: world-time-api
    port:
      number: 443

---
apiVersion: hub.traefik.io/v1
kind: API
metadata:
  name: httpbin-external-name
  namespace: apps
  labels:
    area: external
    external: name
spec:
  pathPrefix: /httpbin
  service:
    openApiSpec:
      url: https://httpbin.org/spec.json
    name: httpbin
    port:
      number: 443
  cors:
    allowCredentials: true
    allowHeaders:
      - '*'
    allowMethods:
      - GET
      - HEAD
      - POST
      - PUT
      - PATCH
      - DELETE
      - CONNECT
      - OPTIONS
      #- TRACE
    allowOriginList:
      - '*'
    maxAge: 0
  headers:
    request:
      set:
        "X-Request-Header": "Extra httpbin request header"
        "X-Username": "Somebody"
      delete:
      - "Unnecessary-Request-Header"
    response:
      set:
        "X-Response-Header": "Extra httpbin response header"
        "X-API-Server": "Traefik Hub"
      delete:
      - "Secret-Response-Header"
