---
apiVersion: v1
kind: Service
metadata:
  name: world-time-api
  namespace: apps
spec:
  type: ExternalName
  externalName: worldtimeapi.org
  ports:
  - port: 443

---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: apps
spec:
  type: ExternalName
  externalName: httpbin.org
  ports:
  - port: 443
