---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
  namespace: monitoring
data:
  prometheus.yaml: |-
    # @see: https://grafana.com/docs/grafana/latest/datasources/prometheus/
    # @see: https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus.monitoring.svc:9090
        editable: true
        orgId: 1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-config
  namespace: monitoring
data:
  hub.yaml: |-
    # @see: https://grafana.com/tutorials/provision-dashboards-and-data-sources/
    # @see: https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards
    apiVersion: 1
    providers:
      - name: Hub API Management Dashboards
        folder: Traefik Hub
        type: file
        orgId: 1
        updateIntervalSeconds: 10
        options:
          path: /dashboards/hub
          foldersFromFilesStructure: false
      - name: Flux Dashboards
        folder: Flux
        type: file
        orgId: 1
        updateIntervalSeconds: 10
        options:
          path: /dashboards/flux
          foldersFromFilesStructure: false      
