name: 🚀 Build/Release docker api-server
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/api-server.yaml'
      - 'api-server/**'
  push:
    branches:
      - master
    paths:
      - '.github/workflow/api-server.yaml'
      - 'api-server/**'
    tags:
      - 'api-server_v[0-9]+.[0-9]+.[0-9]+'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  REGISTRY: ghcr.io
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set up buildx
        uses: docker/setup-buildx-action@v3
      - name: docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/api-server
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=match,pattern=api-server_v\d+.\d+.\d+
            type=raw,value={{branch}}-{{sha}}-{{date 'X'}},enable={{is_default_branch}}
            type=ref,event=pr
      - name: build docker images
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:api-server"
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
